services:
  - type: web
    name: finance-management
    env: node
    plan: free
    buildCommand: npm install --prefix server && npm install --prefix client && npm run build --prefix client
    startCommand: node server/src/server.js
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: MONGODB_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRE
        value: 15m
      - key: JWT_REFRESH_EXPIRE
        value: 7d
      - key: SUPER_ADMIN_EMAIL
        sync: false
      - key: SUPER_ADMIN_PASSWORD
        sync: false
      - key: SUPER_ADMIN_NAME
        value: Super Admin
